version: '3.9'

services:
  backend:
    build: ./backend
    container_name: nest_backend
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: nest_login_project
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_login_project
    ports:
      - '5432:5432' # EXPOSING PORT FOR LOCAL DEV ONLY
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  postgres_data:
